'use client';

import { useState } from 'react';
import type { GeneratedOutfit } from '@/app/page';

interface OutfitGalleryProps {
    outfits: GeneratedOutfit[];
}

export default function OutfitGallery({ outfits }: OutfitGalleryProps) {
    const [fullscreenImage, setFullscreenImage] = useState<string | null>(null);

    return (
        <>
            <div className={`outfit-gallery ${outfits.length > 0 ? 'has-content' : ''}`}>
                {outfits.length === 0 ? null : (
                    outfits.map((outfit) => (
                        <div
                            key={outfit.id}
                            className="outfit-hero-card glass-card"
                            onClick={() => {
                                if (outfit.imageBase64) {
                                    setFullscreenImage(
                                        `data:image/jpeg;base64,${outfit.imageBase64}`
                                    );
                                }
                            }}
                        >
                            {outfit.imageBase64 ? (
                                <img
                                    src={`data:image/jpeg;base64,${outfit.imageBase64}`}
                                    alt={outfit.caption}
                                    className="outfit-hero-image"
                                />
                            ) : (
                                <div className="outfit-placeholder">👗 Generating...</div>
                            )}
                            <div className="outfit-hero-caption glass-panel">
                                <strong>{outfit.caption}</strong>
                                <p>Generated by Haute Couture AI</p>
                            </div>
                        </div>
                    ))
                )}
            </div>

            {/* Fullscreen overlay */}
            {fullscreenImage && (
                <div
                    className="outfit-fullscreen"
                    onClick={() => setFullscreenImage(null)}
                >
                    <img src={fullscreenImage} alt="Generated outfit fullscreen view" />
                </div>
            )}
        </>
    );
}
